### ISSUE TITLE
Item deletion in django 1.5

### ISSUE THREAD

**Issue by rmendocna** [jphalip/django-treemenus#24]
Hi,
Trying to delete an item makes it redirect to homepage, as it says in admin.py.
Running off "commit 4c136a4382f2e75b9af15729f65348c51d51dd7b"
Changed:

```
--- a/treemenus/admin.py
+++ b/treemenus/admin.py
@@ -115,7 +115,7 @@ class MenuAdmin(admin.ModelAdmin):
                 url(r'^item_changelist/$', RedirectView.as_view(url='/'), name='treemenus_menuitem_changelist'),
                 url(r'^item_add/$', RedirectView.as_view(url='/'), name='treemenus_menuitem_add'),
                 url(r'^item_history/(?P<pk>[-\w]+)/$', RedirectView.as_view(url='/'), name='treemenus_menuitem_history'),
-                url(r'^item_delete/(?P<pk>[-\w]+)/$', RedirectView.as_view(url='/'), name='treemenus_menuitem_delete'),
+                url(r'^item_delete/(?P<menu_item_pk>[-\w]+)/$', self.admin_site.admin_view(self.delete_menu_item), name='treemenus_m
             )
         return my_urls + urls

@@ -146,8 +146,10 @@ class MenuAdmin(admin.ModelAdmin):
         menu_item_admin = self.menu_item_admin_class(MenuItem, self.admin_site, menu)
         return menu_item_admin.change_view(request, menu_item_pk, extra_context={'menu': menu})

-    def delete_menu_item(self, request, menu_pk, menu_item_pk):
+    def delete_menu_item(self, request, menu_pk=None, menu_item_pk=None):
         ''' Custom view '''
+        if not menu_pk:
+            menu_pk = MenuItem.objects.select_related('menu').get(id=menu_item_pk).menu.id
         menu = self.get_object_with_change_permissions(request, Menu, menu_pk)
         menu_item_admin = self.menu_item_admin_class(MenuItem, self.admin_site, menu)
```

**Comment by jphalip** [comment]
Hi and thank you for the report! Could you please add a test to this pull request?

**Comment by theninth** [comment]
Also have this problem with latest version. Any clues on it yet?

**Comment by ghost** [comment]
Same problem here with latest version & Python 3 & Django 1.6... 
http://expo-asia.ru/admin/treemenus/menu/item_delete/91/ (item deletion)
http://expo-asia.ru/admin/treemenus/menu/item_history/91/ (item history)
links redirect on homepage

**Comment by jphalip** [comment]
Would it be possible for somebody to write a unit test for this? This would help finding a quicker resolution for this issue. Thanks!

**Comment by kl4us** [comment]
I have the same issue with django==1.6.2, django-treemenus==0.9.0 and python==2.7.3

**Comment by kl4us** [comment]
Anyone has solved the issue? @rmendocna workaround doesn't work for me with django==1.6.2, django-treemenus==0.9.0 and python==2.7.3

**Comment by jphalip** [comment]
Could someone at least write a test case for this? I could then look into implementing a fix for it. Thank you.

**Comment by kl4us** [comment]
I don't know how to create a test case. Substantially when i go to an item admin page the link of the delete button is http://127.0.0.1:8000/admin/treemenus/menu/item_delete/25/ and it redirect to home without deleting the item.

Otherwise, if I manually enter the link, like as http://127.0.0.1:8000/admin/treemenus/menu/1/items/25/delete/, it works perfectly.

**Comment by tcsorrel** [comment]
I added some tests in the pull request #31.
Instead of adding new test cases I duplicated checks for django >=1.4.
For these checks I used reversed URL like admin does when clicking on buttons.
About the fixes : 
I implemented delete and history as discussed here. Unfortunately the redirection fails after deletion : ../../.. doesn't point on expected menu page
